AllCops:
  Exclude:
    - bin/**/*
    - bower_components/**/*
    - node_modules/**/*
  RunRailsCops: true

Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/AndOr:
  Enabled: false

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/ClassCheck:
  EnforcedStyle: kind_of?

Style/CollectionMethods:
  PreferredMethods:
    collect: map
    collect!: map!
    detect: find
    find_all: select

Style/Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/IfUnlessModifier:
  MaxLineLength: 100

Style/Lambda:
  Enabled: false

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%': '{}'
    '%i': '{}'
    '%q': '{}'
    '%Q': '{}'
    '%r': '{}'
    '%s': '{}'
    '%w': '{}'
    '%W': '{}'
    '%x': '{}'

Style/RaiseArgs:
  EnforcedStyle: compact

Style/RegexpLiteral:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/SingleLineBlockParams:
  Enabled: false

Style/SingleLineMethods:
  AllowIfMethodIsEmpty: false

Style/SymbolProc:
  IgnoredMethods: []

Style/WhileUntilModifier:
  MaxLineLength: 100

Metrics/LineLength:
  Max: 100
  AllowURI: true
  URISchemes:
    - http
    - https

Lint/AmbiguousOperator:
  Enabled: false

Lint/DefEndAlignment:
  AlignWith: def
