Marty = require 'marty'

# Use alphabet order
Constants = Marty.createConstants [
  'SET_AUTH_POPUP'

  'APPEND_COMMENTS'

  'SET_CURRENT_USER'

  'SET_HEADER_SECTIONS'

  'SET_LOADER_VISIBILITY'

  'SET_PAGES_COUNT'

  'APPEND_POPUPS'
  'REMOVE_POPUPS'

  'APPEND_RATING_ITEMS'
  'CHANGE_RATING_ITEM'
  'REPLACE_RATING_ITEM'
  'REMOVE_RATING_ITEM'
  'CHANGE_RATING_ITEM_POSITIONS'

  'SET_RATING_UPDATE_STATUS'

  'APPEND_RATINGS'
  'CHANGE_RATING'
  'REPLACE_RATING'
  'REMOVE_RATING'
  'ADD_TAG_TO_RATING'
  'REMOVE_TAG_FROM_RATING'

  'APPEND_SECTIONS'

  'SET_SIMILAR_RATINGS'

  'APPEND_TOASTS'
  'REMOVE_TOASTS'

  'APPEND_WAYPOINT'
  'REMOVE_WAYPOINT'
  'CHANGE_WAYPOINT'

  'APPEND_USERS'
  'CHANGE_USER'
  'REPLACE_USER'
]

module.exports = Constants
