use Mix.Config

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :top, Top.Endpoint,
  http: [port: {:system, "PORT"}],
  url: [host: "appy.gy", port: 80],
  cache_static_manifest: "priv/static/manifest.json"

config :logger,
  level: :info,
  backends: [{LoggerFileBackend, :info},
             {LoggerFileBackend, :error}]

config :logger, :info,
  level: :info
  path: Path.join(__DIR__, "../../log/phoenix_info.log"),

config :logger, :error,
  level: :error
  path: Path.join(__DIR__, "../../log/phoenix_error.log"),

import_config "prod.secret.exs"
